export class Muestra {
    // tslint:disable-next-line:variable-name
    id_muestra: string;
    // tslint:disable-next-line:variable-name
    codigo_m_cliente: string;
    // tslint:disable-next-line:variable-name
    fecha_toma_m: Date;
    // tslint:disable-next-line:variable-name
    tipo_m: string;
    // tslint:disable-next-line:variable-name
    origen_m: string;
    // tslint:disable-next-line:variable-name
    tipoenvase_m: string;
    // tslint:disable-next-line:variable-name
    preservante_m: string;
    // tslint:disable-next-line:variable-name
    tipopreservante_m: number;
    // tslint:disable-next-line:variable-name
    refrigeracion_m: string;
    // tslint:disable-next-line:variable-name
    aux_muestra: string;
    // tslint:disable-next-line:variable-name
    id_factura: string;
    // tslint:disable-next-line:variable-name
    descr_m: number;
    // tslint:disable-next-line:variable-name
    num_muestra_fact: string;
    // tslint:disable-next-line:variable-name
    id_unidad: string;
    // tslint:disable-next-line:variable-name
    id_ti: string;
}
